### ISSUE TITLE
Could we specify to use Chrome when we launch Blockly instead of the default browser

### ISSUE THREAD

**Issue by mbonani** [Mobsya/thymio-blockly-standalone#21]
It seems that the interaction in Firefox or some browser are less stable than in Chrome. Could we specify when we open if Chrome is present on the computer to use it? If not use the default one? People will perhaps not be able to modify the default browser and copy paste the link is not evident for everbody

**Comment by cor3ntin** [comment]
What do you mean by less stable ?
Maybe it would be improved by updating blockly ?

**Comment by mbonani** [comment]
It was not the interaction of Blockly but the interaction with the webbridge.
I see that on a Mac using Firefox, you had to click sometimes twice the play or stop button to have it transfer to the Thymio. It also show strange behavior like you press play, the Thymio works but then you have the warning message"Connect Thymio And Launch Web Bridge"
I see more and more that be compatible with all browser could be annoying and ask if we can do another way. It is perhaps a workaround and not a long term practice, but could help end user more quickly.

**Comment by cor3ntin** [comment]
Even if there was an easy way to do that (there is not - it would take time), I'm not convince that there are a lot of people who install chrome without making it the default browser.

I think it would be quicker to investigate why there are issue on firefox !

**Comment by stephanemagnenat** [comment]
I agree with @cor3ntin, it would be unethical to force people to use Chrome (a company-sponsored browser), that would be strongly against our values and the objectives of the Thymio project.

**Comment by cor3ntin** [comment]
@mbonami what version of c++ are you running? Maybe updating FF helps.

**Comment by mbonani** [comment]
It was last version of FF, with aseba 1.6. I do not understand the C++ version.

**Comment by mbonani** [comment]
probably we will pack it in chromium
