### ISSUE TITLE
Blockly dislplay of images + languages

### ISSUE THREAD

**Issue by cbarraud** [Mobsya/thymio-blockly-standalone#24]
I just tested Blockly (in the 1.6.9 latest build 64 bits) and saw these issues (maybe just linked to the fact that's the work in progress branch):

![image](https://user-images.githubusercontent.com/4930020/51489255-1117e280-1da8-11e9-89c9-a99aac9688ff.png)

- The images (like buttons start/stop, zoom...) are not displayed in any other languages than in English
- There is Spanish as proposed language (is it maintained?)
- The blocks are always in English, whatever the chosen language

**Comment by mbonani** [comment]
all this is corrected
